# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS

FACEBOOK_KEY: "150980305103487" #Prod
FACEBOOK_SECRET: "c0d5dbe06bd54a4c9454a930dd4caa7b" #Prod
DOMAIN_NAME: "karpeer.com"

#FACEBOOK_KEY: "204860239678505" #Dev
#FACEBOOK_SECRET: "0d69121f318c575346431e9368fec75b" #Dev

