FACEBOOK_KEY: "150980305103487" #Prod
FACEBOOK_SECRET: "038485edf6ac3ab3f3e538a07cd8c9af" #Prod
DOMAIN_NAME: "karpeer.com"

#FACEBOOK_KEY: "204860239678505" #Dev
#FACEBOOK_SECRET: "0d69121f318c575346431e9368fec75b" #Dev

OAUTH_CLIENT_ID: "138742328431.apps.googleusercontent.com" #Prod
OAUTH_CLIENT_SECRET: "b_R3YTYmomFxqBft0X8V9bax" #Prod

#OAUTH_CLIENT_ID: "138742328431-0emve0sm30ek6ob7k14jrqpkif1t4o5m.apps.googleusercontent.com" #Dev
#OAUTH_CLIENT_SECRET: "c5yBYP9RBBqBHlNHlRIsZkpp" #Dev
#APPLICATION_CONFIG_SECRET_TOKEN: "c2rbcuXOPNCJ48C2aC"

GMAIL_USER: "karpeer.com@gmail.com"
GMAIL_PASSWD: "h0n3yb@dg3r"
